### ISSUE TITLE
Allow omitting redundant package name

### ISSUE THREAD

**Issue by joewreschnig** [quelpa/quelpa-use-package#10]
In `(use-package foobar :quelpa (foobar :repo ...)))` the `foobar` to `use-package` should always be the same as the `foobar` in the recipe. It would be nicer not to have to specify it twice, and just use `(use-package foobar :quelpa (:repo ...)))`.

Looking in the code, there's already [a case which looks like the intention might be to handle this](https://github.com/quelpa/quelpa-use-package/blob/da359ba400be6326d51e40f28307e48cbbaa13d8/quelpa-use-package.el#L69). However, the `pcase` is on `(car args)` rather than `args`, so `(:repo ...)` gets caught by the `(pred symbolp)` and returns the original argument list instead. However, I'm not sure if this a bug or handling another real situation.

**Comment by steckerhalter** [comment]
The use-case in the code is so that you can pass parameters without specifying the recipe:

```
;; passes upgrade parameter to quelpa
(use-package abc-mode :quelpa (:upgrade t))

**Comment by steckerhalter** [comment]
The use-case in the code is so that you can pass parameters without specifying a recipe:

```cl
;; passes upgrade parameter to quelpa
(use-package abc-mode :quelpa (:upgrade t))
```

I know what you mean but I think it would be kind of inconsistent if we allow to have "incomplete" recipes where full MELPA recipes are expected, but if you want to make a PR for that I think we could add it anyway.

**Comment by joewreschnig** [comment]
Ah, yeah, that makes it much trickier since the structure of both is the same. I guess I'll stick with a couple wrapper macros for now.
