### ISSUE TITLE
It seems to install the elpa package as well

### ISSUE THREAD

**Issue by zoechi** [quelpa/quelpa-use-package#13]
```lisp
(use-package quelpa-use-package
  :ensure t
  :config (setq use-package-ensure-function 'quelpa))

(use-package
  dart-mode
  ;;:ensure t
  :quelpa ((dart-mode :fetcher github
                      :repo "bradyt/dart-mode") :upgrade t)
  :config (setq dart-format-on-save t))
```
Installs the (old) package into `~/.emacs.d/elpa/...` and `~/.emacs.d/quelpa/build/...`
and then the elpa version is loaded, which is what I actually tried to avoid.

Am I doing something wrong?

**Comment by zoechi** [comment]
The GitHub version is not newer than the melpa version anyway, so it doesn't really matter. 
Perhaps you can tell if I'm doing anything wrong anyway. Otherwise feel free to close.

**Comment by kiennq** [comment]
`~/.emacs.d/quelpa/build/...` is just a staging/build folder, whereas `~/.emacs.d/elpa/...` is actually where package is installed and loaded.
`Quelpa` will clone the package into build folder, build it there and install it to elpa folder, does that make sense?

**Comment by steckerhalter** [comment]
@zoechi use-package is installing from elpa as well or what do you mean? what's the "old" package?

**Comment by zoechi** [comment]
For some reason I expected to get a newer version from Github (But Melpa has the latest version. That was my mistake).
Then I saw that the code was loaded from the elpa directory and I assumed this was the cause for not getting a newer version.

Thanks for your explanation, I guess all is fine then.

I got a bit lost in the Emacs config rabbit hole :D

**Comment by steckerhalter** [comment]
@zoechi alright, that can happen :smile: cheers
