### ISSUE TITLE
Quelpa: Fetch repo subdirectory

### ISSUE THREAD

**Issue by firmart** [quelpa/quelpa-use-package#18]
Cross-posted to [spacemacs](https://github.com/syl20bnr/spacemacs/issues/13911).
I raised this issue in the wrong repo, maybe it would worth to wait for an answer from spacemacs.

I wanted to fetch [org-krita](https://github.com/lepisma/org-krita) with
```emacs-lisp
  (use-package org-krita
    :quelpa (org-krita :fetcher git :url "https://github.com/lepisma/org-krita")
    :ensure t)  
```
or 
```emacs-lisp
(use-package org-krita
    :quelpa (org-krita :fetcher github :repo "lepisma/org-krita" )
    :ensure t) 
```
But the important subdirectory `/resources` that must be cloned so that the package works correctly has not been fetched.
Currently, the following packages are installed: 
- `quelpa-use-package` version `20200307.805`
- `quelpa` version `20200903.825`
The problem is that **spacemacs comes along with its own `quelpa` in `core/library`**. I don't know which variant of `quelpa` has been used,  so I posted here the issue. 

Q. How to clone subdirectory with `quelpa` ?

**Comment by kiennq** [comment]
Take a look at this https://github.com/quelpa/quelpa/issues/198
Basically you will need to add a `:files` option

**Comment by firmart** [comment]
Thank you. 
I ended up to use : 
```emacs-lisp
(use-package org-krita
    :ensure t
    :quelpa (org-krita :fetcher github :repo "lepisma/org-krita" :files ("*.el" "resources"))
    :config
    (add-hook 'org-mode-hook 'org-krita-mode))
```

I didn't find `:files` in the README, maybe it would be better to add it?

**Comment by kiennq** [comment]
It's the same format with MELPA recipes. If the README is not mentioned that, can you help provide a PR?

**Comment by firmart** [comment]
Sure, I'll try to do it today.

**Comment by jcs090218** [comment]
I think this can be closed? ;)

**Comment by firmart** [comment]
Indeed, thanks for the reminder.
