### ISSUE TITLE
Add quelpa-use-package to MELPA

### ISSUE THREAD

**Issue by syl20bnr** [quelpa/quelpa-use-package#2]
It would be handy to have quelpa-use-package on MELPA as well. It would simplify the bootstrapping of Spacemacs which uses ELPA repos.

**Comment by steckerhalter** [comment]
I'll be submitting it as soon as possible...

**Comment by steckerhalter** [comment]
https://github.com/milkypostman/melpa/pull/2993

**Comment by steckerhalter** [comment]
it has been merged...
