### ISSUE TITLE
How to copy static files to the "elpa" directory when build finished?

### ISSUE THREAD

**Issue by nicehiro** [quelpa/quelpa-use-package#24]
Quelpa will download the package in "quelpa/build/", and build ".el" and ".elc" files to the "elpa" directory to load it.

Sometimes I need the static files from package, so can I copy the static files when build finished?

Example:
files in quelpa:
![image](https://user-images.githubusercontent.com/17773634/97987846-eda41780-1e16-11eb-9cab-fcccd3e5cd7b.png)
files in elpa:
![image](https://user-images.githubusercontent.com/17773634/97987818-e1b85580-1e16-11eb-9c2e-fecb17a5ed3e.png)

**Comment by jcs090218** [comment]
Can you post your recipe format? Thanks! ;)

**Comment by nicehiro** [comment]
`(use-package elisp-docstring-server
	:quelpa
	(elisp-docstring-server :repo "xuchunyang/elisp-docstring-server.el"
	:fetcher github))
`
Thank you~

**Comment by jcs090218** [comment]
I think you can add `:files` to recipe argument.

For instance, the following recipe copies the whole `sdk` folder to build directory.

```el
(organize-imports-java
 :repo "jcs-elpa/organize-imports-java"
 :fetcher github
 :files (:defaults "sdk"))
```

See if this helps! ;)

**Comment by nicehiro** [comment]
Great! Really thank you!

**Comment by jcs090218** [comment]
Glad this helps! ;)
