### ISSUE TITLE
quelpa :upgrade attribute has no effect in quelpa-use-package

### ISSUE THREAD

**Issue by madscientist** [quelpa/quelpa-use-package#25]
This was working for a while but sometime around last October I realized that my quelpa packages were no longer being updated, and if I delete them they don't get re-installed.  I am using quelpa-use-package to install the newest version of cc-mode, so I have this in my emacs init:
```
(use-package cc-mode
  :ensure t
  :quelpa (cc-mode :fetcher hg
                   :url "http://hg.code.sf.net/p/cc-mode/cc-mode"
                   :upgrade t))
```
This used to work but now is a no-op.  I didn't notice so I'm not sure when it changed but the last time my cc-mode was updated was Oct 2020.  Now when I start Emacs if I look in my messages buffer I see:
```
Newer package has been installed. Not upgrading.
```
and no updates are done.

Debugging shows that the `:upgrade` setting that I've given is ignored, and quelpa's `quelpa-upgrade-p` variable is nil, not t which is what I want, when it runs the `quelpa-build` method.

I was able to force it to install by evaluating this in my scratch buffer:
```
(quelpa '(cc-mode :fetcher hg
                  :url "http://hg.code.sf.net/p/cc-mode/cc-mode")
        :upgrade t)
```
Note, that the `:upgrade` attribute must appear _outside_ of the package definition; it's a plist attribute for the invocation of the quelpa function; an `:upgrade` attribute inside the package definition is ignored.  It seems that the `quelpa-use-package` wrapper isn't managing this attribute as expected?

**Comment by steckerhalter** [comment]
Please reopen if still an issue
