### ISSUE TITLE
github fetcher still installs the existing melpa package

### ISSUE THREAD

**Issue by yayuwang0624** [quelpa/quelpa-use-package#27]
I wanna install my own fork repo instead of the melpa one, but with the following config, use-package still installs the melpa package. Is it the expected behavior or I did something wrong? and what should I do to ignore the existing melpa package?

```elisp
(require 'use-package)
(setq use-package-always-ensure t)

(use-package quelpa
  :config
  (setq quelpa-update-melpa-p t)
  )

(use-package quelpa-use-package
  :init
  (setq use-package-ensure-function 'quelpa)
  :config
  (quelpa-use-package-activate-advice))

(use-package org-pdftools
  :after quelpa quelpa-use-package
  :ensure nil
  :quelpa ((org-pdftools
	    :fetcher github
	    :repo "ST-Saint/org-pdftools"))
  :hook (org-mode . org-pdftools-setup-link))
```

**Comment by doomchild** [comment]
I'm having the same problem.  Did you find an answer to this?

**Comment by steckerhalter** [comment]
Could be that you need to this to override the melpa recipe: https://github.com/quelpa/quelpa#use-local-recipes
Instead of using a path you can add a list with one ore more recipes.

**Comment by doomchild** [comment]
I guess I don't understand why that's necessary if I'm already giving it a recipe, as in:

```
(use-package popup-kill-ring
  :quelpa (popup-kill-ring :fetcher github :repo "doomchild/popup-kill-ring" :branch "support-emacs-29")
  :bind ("M-y" . popup-kill-ring)
  :custom (setq popup-kill-ring-interactive-insert t))
```

Is the value in the `:quelpa` key not a recipe?  What's the point of having the `:fetcher` or `:repo` keys if they aren't actually used to pull the package from somewhere else?  I've forked a package that I'm trying to update to work in 29.1, and it keeps pulling the MELPA package, even though I've explicitly told it here to pull from my repository.

**Comment by steckerhalter** [comment]
I think you need to add `:ensure nil` since use-package is otherwise pulling it from melpa:

```
(use-package popup-kill-ring
  :quelpa (popup-kill-ring :fetcher github :repo "doomchild/popup-kill-ring" :branch "support-emacs-29")
  :ensure nil
  :bind ("M-y" . popup-kill-ring)
  :custom (setq popup-kill-ring-interactive-insert t))
```

At least this has used the correct branch in my test.

I think the issue ST-Saint had is different since he is using `:ensure nil`

@ST-Saint can this issue be closed?

**Comment by doomchild** [comment]
No, using `:ensure nil` still installs the package from the existing recipe; it ignores the recipe given in the `:quelpa` key.  This seems to be the same issue ST-Saint had.  I'm specifying the repo and branch from which to pull the package, but it ignores what I specified and uses the recipe in `~/.emacs.d/quelpa/melpa/recipes`.

**Comment by steckerhalter** [comment]
Ok, I've tested it and for me it installed the version from the branch. I'm not sure why it doesn't work for you. Can you debug it?

**Comment by doomchild** [comment]
I don't know what I'd be debugging or what to look for.  Is there some magic configuration somewhere else that I need?  I'm installing it the same way the docs say, and I've tried it both with and without `(setq use-package-ensure-function 'quelpa)`.  What am I looking for?

Here's the relevant part of my config:

```
(require 'package)

(setq package-enable-at-startup nil)

(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(add-to-list 'package-archives '("elpa" . "http://elpa.gnu.org/packages/") t)
(add-to-list 'package-archives '("org" . "https://orgmode.org/elpa/") t)

(package-initialize)

(when (not package-archive-contents)
  (package-refresh-contents))

(unless (package-installed-p 'use-package)
  (package-install 'use-package))

(require 'use-package)

(unless (package-installed-p 'quelpa)
  (with-temp-buffer
    (url-insert-file-contents "https://raw.githubusercontent.com/quelpa/quelpa/master/quelpa.el")
    (eval-buffer)
    (quelpa-self-upgrade)))

(require 'quelpa)

(quelpa
 '(quelpa-use-package
   :fetcher git
   :url "https://github.com/quelpa/quelpa-use-package.git"))

(require 'quelpa-use-package)

(setq use-package-ensure-function 'quelpa)
```

**Comment by steckerhalter** [comment]
Ah I see, you don't seem to use the advice `quelpa-use-package-activate-advice)` like ST-Saint?
Do you have `use-package-always-ensure` enabled?

**Comment by doomchild** [comment]
I've tried it both ways.

**Comment by steckerhalter** [comment]
Can you create a minimal `.emacs` with your quelpa init code and your repo with the branch and test that? If it doesn't work please post the code here.

**Comment by doomchild** [comment]
Here you go.  This pulls the package from the original author's github instead of from my repository.

```elisp
;;; -*- lexical-binding: t; -*-
;;; main init

(require 'package)

(setq package-enable-at-startup nil)

(add-to-list 'package-archives '("melpa" . "https://melpa.org/packages/") t)
(add-to-list 'package-archives '("elpa" . "http://elpa.gnu.org/packages/") t)
(add-to-list 'package-archives '("org" . "https://orgmode.org/elpa/") t)

(package-initialize)

(when (not package-archive-contents)
  (package-refresh-contents))

(unless (package-installed-p 'use-package)
  (package-install 'use-package))

(require 'use-package)

(unless (package-installed-p 'quelpa)
  (with-temp-buffer
    (url-insert-file-contents "https://raw.githubusercontent.com/quelpa/quelpa/master/quelpa.el")
    (eval-buffer)
    (quelpa-self-upgrade)))

(require 'quelpa)

(quelpa
 '(quelpa-use-package
   :fetcher git
   :url "https://github.com/quelpa/quelpa-use-package.git"))

(require 'quelpa-use-package)

(setq use-package-ensure-function 'quelpa)

(use-package popup-kill-ring
  :after quelpa
  :quelpa (popup-kill-ring :fetcher github :repo "doomchild/popup-kill-ring" :branch "support-emacs-29")
  :ensure nil
  :bind ("M-y" . popup-kill-ring)
  :custom (setq popup-kill-ring-interactive-insert t))
```

**Comment by steckerhalter** [comment]
ok, I think I know why it doesn't work. using your config it also installed the version from master. and I noticed in the `list-packages` that it is listed as `dependency`. it seems that `use-package` installs `popup-kill-ring` as a dependency if you specify `:after quelpa` so then not quelpa installs it but use-package and hence it gets the version defined in the melpa recipe, which is master. can you try it? als `:ensure nil` would not be needed in this config.

**Comment by doomchild** [comment]
That works in my minimal version, but not my full config.  Guess I've got to start cutting it down to figure out where the culprit is.  Thanks.

**Comment by doomchild** [comment]
I figured it out.  In case anybody else runs into this problem, I had `use-package-always-ensure` set to `t`.  Removing this line fixed my problem and installs the package from the desired repository.

**Comment by steckerhalter** [comment]
ok thanks. @ST-Saint I'm closing this issue, if you still need help please reopen.
