### ISSUE TITLE
Automatically install package if not present, like ":ensure t"

### ISSUE THREAD

**Issue by bricewge** [quelpa/quelpa-use-package#4]
Would it be possible to use the `:ensure t` in a quelpa recipe, or an other keyword, for the package to be installed automatically if it isn't already? 
I know I can use `:upgrade t` to achieve this but I don't want to updated it every time I run emacs. I just want it to be install my package with quelpa if it is not present.

**Comment by steckerhalter** [comment]
Isn't that the default behavior? At least that's what I think it should do... install the package if it isn't yet there.

**Comment by vyp** [comment]
Yes I'm not sure if I'm misinterpreting the question, but just by putting `:quelpa` itself in your `use-package` declaration, it should use quelpa to install the package if it isn't already. i.e. `:quelpa` is like the quelpa-use-package equivalent to use-package's `:ensure t`. At least that's how I understand it.

**Comment by bricewge** [comment]
Oh I'm sorry, you are right. I tried the example with `abc-mode` it worked as expected...

 My only use of `quelpa-use-package` was for `tramp` which is a built-in package of Emacs, so it doesn't install automatically because another version of it is already present.

So my request is more; could you add support to the keyword `:pin quelpa` to force the install of the package from `quelpa` and not use a version from another source? To make something like the following working:

``` emacs-lisp
  (use-package tramp
    :quelpa (tramp :fetcher git
                    :url "git://git.savannah.gnu.org/tramp.git"
                    :files ("lisp/*.el"))
    :pin quelpa)
```

By the way should I open another issue or edit this one?

**Comment by steckerhalter** [comment]
I guess this feature needs to be added to quelpa itself since it requires its code to be extended/changed. So please open an issue there and close this one, thanks.
