### ISSUE TITLE
Allow for the use of expressions rather than stringp

### ISSUE THREAD

**Issue by jmacdonagh** [quelpa/quelpa-use-package#6]
Apologies in advance if I use the wrong terminology. I'm very new to elisp, but after searching and [asking](https://www.reddit.com/r/emacs/comments/48dh7x/evaluating_a_macro_parameter_before_expansion/) it seems that I'm hitting a bug in either `quelpa` or `quelpa-use-package`.

I'm trying to do this:

```
(use-package evil-org :ensure nil
 :quelpa (evil-org
    :fetcher file
    :path (concat my-package-directory "evil-org")))
```

and getting

```
Quelpa: failed to checkout `evil-org': `Wrong type argument: stringp, (concat my-package-directory "evil-org")'
```

From some fairly generic searching I've also tried

```
,(concat my-package-directory "evil-org")
```

and

```
`(,(concat my-package-directory "evil-org"))
```

but none work.

On a regular `quelpa` function call this works (which is why I'm submitting this issue here):

```
(quelpa `(evil-org :fetcher file :path ,(concat my-package-directory "evil-org")))
```

And if I really want to make things messy I can do this:

```
(eval `(use-package evil-org
  :ensure nil
  :quelpa (evil-org
        :fetcher file
        :path ,(concat my-package-directory "evil-org")))
```

Is there some magic syntax I'm missing to make that `concat` evaluate before being expanded into the macro?

Thanks!

**Comment by steckerhalter** [comment]
I think the problem is that `use-package` is itself a macro. I currently don't have time to look into it more closely. What you could do is to define your own recipes. This is currently not documented in the README, but see here: https://github.com/quelpa/quelpa/blob/master/quelpa.el#L96

Try also  `M-x customize-variable RET quelpa-melpa-recipe-stores RET`

You can put your recipes into a list or a directory and then with

``` cl
(use-package evil-org :quelpa)
```

quelpa will load your recipe defined for `evil-org`.

**Comment by jmacdonagh** [comment]
Thanks for the response. Unfortunately, your suggestion for putting the recipe in a separate file didn't seem to help. Putting this in a recipe file (and adding the directory it sits in to `quelpa-melpa-recipe-stores`) didn't work:

```
(evil-org :fetcher file :path (concat my-package-directory "evil-org"))
```

It has the same error, no `stringp`. If I hardcode the path in there instead of the concat it works. Any relative paths seem to be relative to the working directory of Emacs, not the recipe file itself (I need this config to work across multiple machines so hardcoding a path won't work).

I also tried:

```
`(evil-org :fetcher file :path ,(concat my-package-directory "evil-org"))
```

But still no go.

I can work around this with an eval for now. I'll keep this ticket open for now until you have some spare cycles to look at it. Let me know if it's more of a `use-package` bug than a `quelpa-use-package` one. Thanks!

**Comment by steckerhalter** [comment]
Right, I forgot that it's of course not evaled either like that. Can you use the home directory as a basis?

(use-package evil-org :ensure nil
 :quelpa (evil-org
    :fetcher file
    :path "~/my/path/evil-org")))

or the other solution would be:

``` cl
(add-to-list 'quelpa-melpa-recipe-stores
             `((evil-org :fetcher file :path ,(expand-file-name "evil-org" my-package-directory))
               (next-recipe ...)))

;; and then
(use-package evil-org :quelpa)
```

**Comment by jmacdonagh** [comment]
Oh I'm sorry, when I read in the .el that it could be a "list" I thought it means a list of directories (still new to elisp). Your second solution above works perfectly and does exactly what I want.

I'm not sure if you consider the original problem statement (can't expand in use-package macro) a bug or not. If not, feel free to close this.

Thanks!
