### ISSUE TITLE
Add something similar to `use-package-always-ensure` for quelpa

### ISSUE THREAD

**Issue by belak** [quelpa/quelpa-use-package#7]
I'd like to install most of my packages from quelpa without having to specify `a bare :quelpa` in all of them.

`use-package-always-ensure` currently will add an `:ensure t` or something similar, to each block implicitly if it doesn't already specify `:ensure`

**Comment by steckerhalter** [comment]
Right, i guess it's no big deal for `use-package` to add something like that but it's a bit more difficult to do that from our package since we do not control `use-package` directly. I guess some advice could manage it but that would need some research and I'm currently quite absorbed by other things. I will look into it sometimes if I can.

**Comment by dsedivec** [comment]
I whipped this up real quick tonight, though I'd post it here in case anyone else finds it useful.  I've only tried it a very little bit but I've installed a few packages with it already.  Heavily borrowed from quelpa-use-package and use-package.  Will only work under Emacs 25.

```elisp
(defgroup quelpa-use-package nil
  "Adds quelpa functionality to use-package."
  :group 'startup)

(defcustom quelpa-use-package-always-quelpa nil
  "Treat every package as though it had specified `:quelpa SEXP`."
  :type 'sexp
  :group 'quelpa-use-package)

(define-advice use-package (:filter-args
                            (arg-list)
                            quelpa-use-package-always-quelpa)
  (if quelpa-use-package-always-quelpa
      (cons (car arg-list)
            (use-package-plist-maybe-put
             (cdr arg-list) :quelpa quelpa-use-package-always-quelpa))
    arg-list))
```

Maybe I should submit this as a pull request (including documentation)?  I could probably fall back on `defadvice` instead of `define-advice`, too, to throw the Emacs 24 users a bone.

**Comment by belak** [comment]
It may be possible to use this to hook into quelpa somehow: 

https://github.com/jwiegley/use-package/pull/427

**Comment by steckerhalter** [comment]
Thanks, that would be much cleaner then.

**Comment by raxod502** [comment]
See also https://github.com/jwiegley/use-package/pull/426.

**Comment by steckerhalter** [comment]
Finally coming around to this... let's say we set `use-package-ensure-function`...

So a new var `quelpa-use-package-ensure` defaults to `nil`, when `t` both `:ensure t` and `use-package-always-ensure` would trigger quelpa.

Now we could even fall back to `package.el` if there is no recipe found. Let's say if `quelpa-use-package-ensure` is `'fallback` then it would first try quelpa and then package.el?

Or would you rather have it fallback by default and have `'nofallback` or something as third option?

**Comment by raxod502** [comment]
Well, in the meantime the entire codebase of `use-package` has been completely refactored. Here is what I would recommend now, having participated in the discussion of how to handle the `use-package` integration for `straight.el` post-refactor:

* Add `:quelpa` to `use-package-keywords`.
* Define `use-package-normalize/:quelpa` and `use-package-handler/:quelpa`.
* Add variable `quelpa-use-package-by-default` or similar.
* Add entry to `use-package-defaults`.

In particular, don't use advice and don't mess with `use-package-ensure-function`.

**Comment by steckerhalter** [comment]
@raxod502 these functions and the keyword are are already present. I played a bit with. All that is needed is:

(setq use-package-ensure-function 'quelpa)

then `:ensure t` uses quelpa and setting `use-package-always-ensure` to `t` uses quelpa too. I'll document that and maybe add a fallback version later...

**Comment by raxod502** [comment]
OK. This is not supported by `use-package` upstream, IIUC. The officially supported solution would not require any advice, but as I don't use `quelpa-use-package` I don't mind.

cc @jwiegley

**Comment by steckerhalter** [comment]
@raxod502 it doesn't require any advice, the advice is for another use-case and not needed for this

@belak documented this in the [readme](https://github.com/quelpa/quelpa-use-package#using-quelpa-with-ensure)

**Comment by raxod502** [comment]
OK, however I think there should still be a way to have `:quelpa t` happen by default without overriding `:ensure`. There currently is not. It would be easy to fix by adding a new variable and registering an entry in `use-package-defaults`.

**Comment by steckerhalter** [comment]
Hmm, maybe that would be better indeed since `:ensure t` would still be available to use `package.el`, thanks. I'll think about it...
