### ISSUE TITLE
how do I specify a specific branch for a git repo?

### ISSUE THREAD

**Issue by ninrod** [quelpa/quelpa-use-package#8]
Suppose I want to grab the `evil-compat` branch from https://github.com/myrjola/multiple-cursors.el, which provides a compatibility layer for evil. 

how can I specify this specific branch? I was thinking in something like this:

``` lisp
(use-package multiple-cursors
  :ensure nil
  :quelpa (multiple-cursors
           :fetcher github
           :repo "myrjlola/multiple-cursors.el"
           :branch "evil-compat"))
```

**Comment by steckerhalter** [comment]
Right, it should work according to: https://github.com/melpa/melpa#recipe-format

**Comment by steckerhalter** [comment]
maybe you are having another `muliple-cursors` still installed with a more recent commit or something?

**Comment by ninrod** [comment]
hi @steckerhalter. so instead of `:branch` I should use really `:version-regexp`, right? I thought that was just to specify `tags`, not `branches`. 

I don't have a version of multiple-cursors installed yet.

**Comment by steckerhalter** [comment]
Not sure if that's what it's supposed to do. I haven't used that option yet :)

Do you get any error btw?

**Comment by ninrod** [comment]
actually that worked.
:version-regexp is the answer.

 all hell is breaking loose because of ivy. Ivy is doing some sort of stuff on top of multiple cursors.

But I think we can close this.

**Comment by steckerhalter** [comment]
@ninrod allright, thanks and have a nice time :)
